Repository LLNL/libROM, pull requests merged in 2023-07, with the labels that each got.

#224 StaticSVD supports for transposed SVD + minor fixes on SVD classes
  .github/workflows/run_tests/action.yml
  README.md
  docker/Dockerfile
  examples/dmd/heat_conduction_dmdc.cpp
  lib/CMakeLists.txt
  lib/algo/DMD.cpp
  lib/linalg/Matrix.cpp
  lib/linalg/Matrix.h
  lib/linalg/svd/RandomizedSVD.cpp
  lib/linalg/svd/RandomizedSVD.h
  lib/linalg/svd/StaticSVD.cpp
  lib/utils/mpi_utils.cpp
  lib/utils/mpi_utils.h
  unit_tests/test_Matrix.cpp
  unit_tests/test_RandomizedSVD.cpp
  unit_tests/test_StaticSVD.cpp
Labels: bug, enhancement, RFR

#227 IncrementalSVDFastUpdate with faster updates + bug fix in IncrementalSVD
  .github/workflows/run_tests/action.yml
  CMakeLists.txt
  lib/CMakeLists.txt
  lib/linalg/BasisGenerator.cpp
  lib/linalg/Options.h
  lib/linalg/svd/IncrementalSVD.cpp
  lib/linalg/svd/IncrementalSVDBrand.cpp
  lib/linalg/svd/IncrementalSVDBrand.h
  unit_tests/test_IncrementalSVDBrand.cpp
Labels: bug, enhancement, RFR, Test

#231 Add matrix row/column rescaling methods
  lib/linalg/Matrix.cpp
  lib/linalg/Matrix.h
Labels: enhancement, RFR
