Repository LLNL/libROM, pull requests merged in 2024-01, with the labels that each got.

#258 Sample mesh manager bug fix
  examples/prom/dg_advection_global_rom.cpp
  examples/prom/linear_elasticity_global_rom.cpp
  examples/prom/maxwell_global_rom.cpp
  examples/prom/poisson_global_rom.cpp
  examples/prom/poisson_local_rom_greedy.cpp
  lib/mfem/SampleMesh.cpp
Labels: RFR

#218 Enable EQP for nonlinear elastic example
  examples/prom/nonlinear_elasticity_global_rom.cpp
  examples/prom/nonlinear_elasticity_global_rom_eqp.hpp
Labels: enhancement

#260 Add global pROM example for grad-div problem
  CMakeLists.txt
  examples/prom/grad_div_global_rom.cpp
Labels: RFR

#250 De advection greedy
  CMakeLists.txt
  examples/dmd/de_dg_advection_greedy.cpp
Labels: RFR

#255 Double pass Gram-Schmidt methods
  lib/linalg/Matrix.cpp
  lib/linalg/Matrix.h
  unit_tests/test_Matrix.cpp
Labels: enhancement, RFR

#254 DE parametric maxwell greedy
  CMakeLists.txt
  examples/prom/de_parametric_maxwell_greedy.cpp
Labels: RFR
