Repository LLNL/libROM, pull requests merged in 2024-03, with the labels that each got.

#271 minor fix and a unit test for NNLSSolver
  .github/workflows/run_tests/action.yml
  CMakeLists.txt
  lib/linalg/NNLS.cpp
  lib/linalg/NNLS.h
  unit_tests/test_NNLS.cpp
Labels: RFR, Test

#253 Refactor examples
  examples/dmd/dg_advection.cpp
  examples/dmd/dg_euler.cpp
  examples/dmd/heat_conduction.cpp
  examples/dmd/heat_conduction_dmdc.cpp
  examples/dmd/nonlinear_elasticity.cpp
  examples/dmd/wave_equation.cpp
  examples/misc/combine_samples.cpp
  examples/prom/dg_advection_global_rom.cpp
  examples/prom/mixed_nonlinear_diffusion.cpp
  examples/prom/nonlinear_elasticity_global_rom.cpp
  lib/linalg/BasisGenerator.cpp
  lib/linalg/BasisGenerator.h
Labels: RFR

#274 MPIO support for Basis classes
  .github/workflows/run_tests/action.yml
  CMakeLists.txt
  docker/Dockerfile
  lib/CAROM_config.h.in
  lib/CMakeLists.txt
  lib/linalg/BasisGenerator.cpp
  lib/linalg/BasisGenerator.h
  lib/linalg/BasisReader.cpp
  lib/linalg/BasisReader.h
  lib/linalg/BasisWriter.cpp
  lib/linalg/BasisWriter.h
  lib/linalg/svd/SVD.h
  lib/linalg/svd/StaticSVD.cpp
  lib/utils/CSVDatabase.cpp
  lib/utils/CSVDatabase.h
  lib/utils/Database.cpp
  lib/utils/Database.h
  lib/utils/HDFDatabase.cpp
  lib/utils/HDFDatabase.h
  lib/utils/HDFDatabaseMPIO.cpp
  lib/utils/HDFDatabaseMPIO.h
  lib/utils/mpi_utils.cpp
  lib/utils/mpi_utils.h
  unit_tests/test_HDFDatabase.cpp
Labels: enhancement, RFR
